#!/bin/sh


if [ $# -ne 1 ]; then
    echo "Usage: $0 <cm12.img>"
fi

# Extract name wihtout zip
FNAME=${1##*/}
DIR=`echo ${FNAME%.zip}`

# Make folder and unzip
rm -rf /tmp/$DIR
mkdir /tmp/$DIR
cd /tmp/$DIR
unzip $1

# decompress image
java -jar $HOME/bin/SDA2Image.jar system.transfer.list system.new.dat system.img

# mount the new image
mkdir -p mnt_img
sudo mount -t ext4 -o loop,ro,noexec,noload system.img mnt_img

